### ISSUE TITLE
ditch PHP dependency

### ISSUE THREAD

**Issue by DreadKnight** [FreezingMoon/FreezingMoon.github.io#1]
In order to have this freely hosted here on GitHub (pages), it should become a static website, so PHP dependency must be eliminated. Website could be generated using Node.js and Grunt or some templating system perhaps.

**Comment by BaibhaVatsa** [comment]
Perhaps something like [Gatsby](https://www.gatsbyjs.org/) could be used to generate the pages and link it with [GitHub Pages](https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/).

**Comment by DreadKnight** [comment]
@BaibhaVatsa Will eventually have the website part revamped and mostly merged into the game itself once again at some point. Thanks for the suggestions though :)

**Comment by DreadKnight** [comment]
Revamped the website (also simplified) and got rid of all the PHP in c5e8a46536640e5a06ae98a3de83635eb3fb9513
